# Generated by Django 4.2.23 on 2025-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SITTING_ANIMAL', 'Sitting Animal'), ('YOGA_BOWLS', 'Yoga Bowls'), ('PER_DAY', 'Per Day'), ('YOGA_ANIMALS', 'Yoga Animals'), ('CHOPSTICK_HOLDERS', 'Chopstick Holders'), ('STANDING_ANIMAL', 'Standing Animal'), ('BOTTLE_CORKS', 'Bottle Corks'), ('SANTA_YOGA_BOWLS', 'Santa Yoga Bowls'), ('SANTA_YOGA_ANIMALS', 'Santa Yoga Animals'), ('HEAD_BOWLS', 'Head Bowls'), ('DRINKING_BOWLS', 'Drinking Bowls'), ('ANIMAL_MASKS', 'Animal Masks'), ('CHOPSTICK_HEADS', 'Chopstick Heads'), ('CHESS_UNITS', 'Chess Units'), ('STOOL_SET', 'Stool Set'), ('SALAD_SERVERS_PAIR', 'Salad Servers (in pairs)'), ('WALKING_ANIMAL', 'Walking Animal'), ('PLACE_CARD_HOLDER', 'Place Card Holder'), ('SANTA_ANIMALS', 'Santa Animals'), ('SUGAR_SPOONS', 'Sugar Spoons'), ('COCKTAIL_STICKS', 'Cocktail Sticks'), ('KEY_HOLDERS', 'Key Holders'), ('FLAT_MAGNETS', 'Flat Magnets'), ('PLAY_ANIMALS', 'Play Animals'), ('CHOPSTICKS', 'Chopsticks'), ('X_MAS_DECO', 'X-Mas Deco'), ('FORKS', 'Forks'), ('BUTTER_KNIFE', 'Butter Knife'), ('LETTER_OPENER', 'Letter Opener'), ('JAM_SCOOPERS', 'Jam Scoopers'), ('NAPKIN_HOLDERS', 'Napkin Holders'), ('HAIR_COMBS', 'Hair Combs'), ('PAPER_WEIGHTS', 'Paper Weights'), ('TRAINING_CHOPSTICKS', 'Training Chopsticks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_category',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('WITH CLOTHES', 'With Clothes'), ('WITH DRESS', 'With Dress'), ('WITH SUIT', 'With Suit'), ('WITH OVERALL', 'With Overall'), ('4IN', '4 Inch'), ('8X8', '8x8'), ('6X6', '6x6'), ('5X4', '5x4'), ('XMAS DRESS', 'Xmas Dress'), ('IN PAIRS', 'In Pairs'), ('12IN', '12 Inch'), ('8IN', '8 Inch'), ('N/A', 'Not Applicable'), ('2D', '2D'), ('3D', '3D'), ('SHORT', 'Short'), ('LONG', 'Long'), ('THIN TIP', 'Thin Tip'), ('THICK TIP', 'Thick Tip'), ('NORMAL', 'Normal'), ('BOTTOMS UP', 'Bottoms Up')], default='MEDIUM', max_length=20),
        ),
    ]
