# Generated by Django 4.2.23 on 2025-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('ITEMS', 'Items'), ('PAIRS', 'Pairs')], default='ITEMS', max_length=10),
        ),
    ]
