# Generated by Django 4.2.23 on 2025-09-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
