# Generated by Django 5.2.17 on 2026-09-10 14:13

from django.db import migrations


def populate_lookups(apps, schema_editor):
    ProductType = apps.get_model('products', 'ProductType')
    ServiceCategory = apps.get_model('products', 'ServiceCategory')
    SizeCategory = apps.get_model('products', 'SizeCategory')
    Product = apps.get_model('products', 'Product')

    # Hardcoded lists from previous implementation
    PRODUCT_TYPES = [
        ('SITTING_ANIMAL', 'Sitting Animal'),
        ('YOGA_BOWLS', 'Yoga Bowls'),
        ('PER_DAY', 'Per Day'),
        ('YOGA_ANIMALS', 'Yoga Animals'),
        ('CHOPSTICK_HOLDERS', 'Chopstick Holders'),
        ('STANDING_ANIMAL', 'Standing Animal'),
        ('BOTTLE_CORKS', 'Bottle Corks'),
        ('SANTA_YOGA_BOWLS', 'Santa Yoga Bowls'),
        ('SANTA_YOGA_ANIMALS', 'Santa Yoga Animals'),
        ('HEAD_BOWLS', 'Head Bowls'),
        ('DRINKING_BOWLS', 'Drinking Bowls'),
        ('ANIMAL_MASKS', 'Animal Masks'),
        ('CHOPSTICK_HEADS', 'Chopstick Heads'),
        ('CHESS_UNITS', 'Chess Units'),
        ('STOOL_SET', 'Stool Set'),
        ('SALAD_SERVERS_PAIR', 'Salad Servers (in pairs)'),
        ('WALKING_ANIMAL', 'Walking Animal'),
        ('PLACE_CARD_HOLDER', 'Place Card Holder'),
        ('SANTA_ANIMALS', 'Santa Animals'),
        ('SUGAR_SPOONS', 'Sugar Spoons'),
        ('COCKTAIL_STICKS', 'Cocktail Sticks'),
        ('KEY_HOLDERS', 'Key Holders'),
        ('FLAT_MAGNETS', 'Flat Magnets'),
        ('PLAY_ANIMALS', 'Play Animals'),
        ('CHOPSTICKS', 'Chopsticks'),
        ('X_MAS_DECO', 'X-Mas Deco'),
        ('FORKS', 'Forks'),
        ('BUTTER_KNIFE', 'Butter Knife'),
        ('LETTER_OPENER', 'Letter Opener'),
        ('JAM_SCOOPERS', 'Jam Scoopers'),
        ('NAPKIN_HOLDERS', 'Napkin Holders'),
        ('HAIR_COMBS', 'Hair Combs'),
        ('PAPER_WEIGHTS', 'Paper Weights'),
        ('TRAINING_CHOPSTICKS', 'Training Chopsticks'),
    ]
    
    SERVICE_CATEGORIES = [
        ('DRAWING', 'Drawing'),
        ('CARVING', 'Carving'),
        ('CUTTING', 'Cutting'),
        ('GOUGING', 'Gouging'),
        ('SANDING', 'Sanding'),
        ('PAINTING', 'Painting'),
        ('FINISHING', 'Finishing'),
        ('FINISHED', 'Finished'),
    ]
    
    SIZE_CATEGORIES = [
        ('SMALL', 'Small'),
        ('MEDIUM', 'Medium'),
        ('LARGE', 'Large'),
        ('WITH CLOTHES', 'With Clothes'),
        ('WITH DRESS', 'With Dress'),
        ('WITH SUIT', 'With Suit'),
        ('WITH OVERALL', 'With Overall'),
        ('4IN', '4 Inch'),
        ('8X8', '8x8'),
        ('6X6', '6x6'),
        ('5X4', '5x4'),
        ('XMAS DRESS', 'Xmas Dress'),
        ('IN PAIRS', 'In Pairs'),
        ('12IN', '12 Inch'),
        ('8IN', '8 Inch'),
        ('N/A', 'Not Applicable'),
        ('2D', '2D'),
        ('3D', '3D'),
        ('SHORT', 'Short'),
        ('LONG', 'Long'),
        ('THIN TIP', 'Thin Tip'),
        ('THICK TIP', 'Thick Tip'),
        ('NORMAL', 'Normal'),
        ('BOTTOMS UP', 'Bottoms Up'),
    ]

    for code, display in PRODUCT_TYPES:
        ProductType.objects.get_or_create(name=code, defaults={'display_name': display})
        
    for code, display in SERVICE_CATEGORIES:
        ServiceCategory.objects.get_or_create(name=code, defaults={'display_name': display})
        
    for code, display in SIZE_CATEGORIES:
        SizeCategory.objects.get_or_create(name=code, defaults={'display_name': display})

    # Link existing products to the newly created product types and size categories
    for product in Product.objects.all():
        if product.product_type:
            pt, _ = ProductType.objects.get_or_create(name=product.product_type, defaults={'display_name': product.product_type})
            product.product_type_fk = pt
        if product.size_category:
            sc, _ = SizeCategory.objects.get_or_create(name=product.size_category, defaults={'display_name': product.size_category})
            product.size_category_fk = sc
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producttype_servicecategory_sizecategory_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_lookups),
    ]
