# Generated by Django 5.2.17 on 2026-09-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_populate_lookup_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_product_2d36b6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type_fk',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_category_fk',
            new_name='size_category',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_type', 'animal_type', 'size_category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'animal_type'], name='products_pr_product_8d7b6a_idx'),
        ),
    ]
