services:
  # Backend
  - type: web
    name: kichaka-poa-backend
    env: python
    rootDir: myapp/appback
    buildCommand: ./render_build.sh
    startCommand: gunicorn appback.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://avnadmin:AVNS_Z1NIEnRHAt2_uwx06CM@pg-21c9d5e1-gk-40.d.aivencloud.com:24385/defaultdb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Update with your Render domain


