services:
  # Backend
  - type: web
    name: kichaka-poa-backend
    env: python
    rootDir: myapp/appback
    buildCommand: ./render_build.sh
    startCommand: gunicorn appback.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: # Put your DB name if within Render, otherwise use secret
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Update with your Render domain

  # Frontend
  - type: web
    name: kichaka-poa-frontend
    env: node
    rootDir: myapp/my-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: # URL of the backend service (e.g., https://kichaka-poa-backend.onrender.com/api/)
      - key: AUTH_SECRET
        generateValue: true
      - key: AUTH_URL
        value: # URL of this frontend service (e.g., https://kichaka-poa-frontend.onrender.com)
