# Generated by Django 4.2.23 on 2025-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_finishedstock_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedstock',
            options={'ordering': ['id'], 'verbose_name_plural': 'Finished Stock'},
        ),
        migrations.AddField(
            model_name='finishedstock',
            name='last_audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
