# Generated by Django 4.2.23 on 2025-10-29 16:24

from django.db import migrations


def convert_quantities_to_individual_items(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Inventory = apps.get_model('inventory', 'Inventory')
    FinishedStock = apps.get_model('inventory', 'FinishedStock')

    # Convert Inventory quantities
    for inventory_item in Inventory.objects.all():
        if inventory_item.product.unit_of_measure == 'PAIRS':
            inventory_item.quantity *= 2
            inventory_item.save()

    # Convert FinishedStock quantities
    for finished_stock_item in FinishedStock.objects.all():
        if finished_stock_item.product.unit_of_measure == 'PAIRS':
            finished_stock_item.quantity *= 2
            finished_stock_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_finishedstock_options_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_quantities_to_individual_items),
    ]
