# Generated by Django 4.2.23 on 2025-11-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobdelivery_delivery_date'),
        ('inventory', '0006_convert_pairs_to_individual_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventory')),
                ('job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='jobs.jobitem')),
            ],
            options={
                'verbose_name_plural': 'Inventory Reservations',
                'indexes': [models.Index(fields=['job_item'], name='inventory_i_job_ite_053387_idx'), models.Index(fields=['inventory'], name='inventory_i_invento_e1427c_idx'), models.Index(fields=['status'], name='inventory_i_status_e748a8_idx')],
            },
        ),
    ]
