# Generated by Django 4.2.26 on 2026-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
    ]
