# Generated by Django 4.2.23 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
    ]
