# Generated by Django 4.2.23 on 2025-11-11 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='payslips/')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_advances_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artisans.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='artisans.artisan')),
            ],
            options={
                'verbose_name': 'Artisan Advance',
                'verbose_name_plural': 'Artisan Advances',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_deducted', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='financials.artisanadvance')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_deductions', to='financials.payslip')),
            ],
            options={
                'verbose_name': 'Advance Deduction',
                'verbose_name_plural': 'Advance Deductions',
                'ordering': ['-date_deducted'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], help_text='The stage/service category this rate is for (e.g., CARVING, PAINTING).', max_length=50)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='The rate paid to an artisan per unit of this product for this service category.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service rate is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this service rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='payslip_service_rates', to='products.product')),
            ],
            options={
                'verbose_name': 'Service Rate',
                'verbose_name_plural': 'Service Rates',
                'ordering': ['product__product_type', 'product__animal_type', 'service_category'],
                'unique_together': {('product', 'service_category')},
            },
        ),
    ]
