# Generated by Django 4.2.23 on 2025-11-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='pdf_file',
            new_name='spreadsheet_file',
        ),
    ]
