# Generated by Django 4.2.23 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_rename_pdf_file_payslip_spreadsheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='service_category',
            field=models.CharField(blank=True, choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], help_text='The stage/service category this rate is for (e.g., CARVING, PAINTING).', max_length=50),
        ),
    ]
