# Generated by Django 5.2.12 on 2026-05-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_payslip_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancededuction',
            name='date_deducted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artisanadvance',
            name='date_given',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
