# Generated by Django 5.2.12 on 2026-03-23 10:22

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_order_subtotal_and_more'),
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
