# Generated by Django 4.2.23 on 2025-09-12 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_servicerate_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
