# Generated by Django 4.2.23 on 2025-09-18 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdelivery',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
