# Generated by Django 4.2.23 on 2025-11-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
        ('jobs', '0007_alter_jobdelivery_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50)),
                ('to_stage', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jobs.job')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_transactions', to='products.product')),
            ],
            options={
                'verbose_name': 'Job Transaction',
                'verbose_name_plural': 'Job Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
