# Generated by Django 4.2.23 on 2025-11-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
        ('jobs', '0008_jobtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtransaction',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_transactions', to='products.product'),
        ),
    ]
