# Generated by Django 4.2.23 on 2025-11-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobtransaction_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='from_stage',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='to_stage',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
    ]
