# Generated by Django 4.2.23 on 2026-02-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_order_subtotal_and_more'),
        ('jobs', '0010_alter_job_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='orders.order'),
        ),
    ]
