# Generated by Django 4.2.23 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='order',
        ),
        migrations.AlterField(
            model_name='job',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='from_stage',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='to_stage',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='service_category',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('GOUGING', 'Gouging'), ('SANDING', 'Sanding'), ('PAINTING', 'Painting'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
    ]
