# Generated by Django 5.2.12 on 2026-03-23 10:22

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_order_alter_job_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='unit_price_at_creation',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=50),
        ),
        migrations.RemoveField(
            model_name='jobitem',
            name='original_amount',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='original_amount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity_ordered'), '*', models.F('unit_price_at_creation')), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
    ]
