# Generated by Django 5.2.12 on 2026-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobitem_unit_price_at_creation_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
