# Generated by Django 5.2.12 on 2026-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobitem_final_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='total_final_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
