# Generated by Django 5.2.12 on 2026-05-17 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_total_cost_job_total_final_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed')], db_column='status', default='IN_PROGRESS', max_length=50),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='_status',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobdelivery',
            name='delivery_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobtransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
